# Restaurant Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-pod
  template:
    metadata:
      labels:
        app: orders-pod
    spec:
      containers:
        - name: orders-pod
          image: mkiesinski/orderservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name:
    orders-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: orders-pod
  ports:
    - name: orders-pod
      protocol: TCP
      port: 80
      targetPort: 80
    - name: orders-grpc
      protocol: TCP
      port: 8888
      targetPort: 8888