apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigw-pod
  template:
    metadata:
      labels:
        app: apigw-pod
    spec:
      containers:
        - name: apigw-pod
          image: mkiesinski/ocelotapigw:latest
---
apiVersion: v1
kind: Service
metadata:
  name:
    apigw-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: apigw-pod
  ports:
    - name: apigw-pod
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apigw-node-service
spec:
  type: NodePort
  selector:
    app: apigw-pod
  ports:
    - name: apigw-pod
      protocol: TCP
      port: 80
      targetPort: 80