apiVersion: v1
kind: Service
metadata:
  name: restaurantservice-service
spec:
  type: NodePort
  selector:
    app: restaurantservice
  ports:
    - name: restaurantservice
      protocol: TCP
      port: 80
      targetPort: 80