apiVersion: v1
kind: Service
metadata:
  name: restaurants-node-service
spec:
  type: NodePort
  selector:
    app: restaurants-pod
  ports:
    - name: restaurants-pod
      protocol: TCP
      port: 80
      targetPort: 80