# Restaurant Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurants-pod
  template:
    metadata:
      labels:
        app: restaurants-pod
    spec:
      containers:
        - name: restaurants-pod
          image: mkiesinski/restaurantservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name:
    restaurants-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: restaurants-pod
  ports:
    - name: restaurants-pod
      protocol: TCP
      port: 80
      targetPort: 80