apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: lagun.devel
      http:
        paths:
          - path: /api/v1/restaurants
            pathType: Prefix
            backend:
              service:
                name: restaurants-clusterip-service
                port: 
                  number: 80
          - path: /api/v1/u/restaurants
            pathType: Prefix
            backend:
              service:
                name: users-clusterip-service
                port:
                  number: 80
          - path: /api/v1/users
            pathType: Prefix
            backend:
              service:
                name: users-clusterip-service
                port:
                  number: 80